### ISSUE TITLE
Error: You should not call `create` on a model

### ISSUE THREAD

**Issue by jwright04** [toranb/ember-cli-simple-store#60]
Finally had an opportunity to try this out.  I'm trying to push a response object to simpleStore but I'm running into the following error:

> Error: You should not call `create` on a model. Instead, call `store.createRecord` with the attributes you would like to set.

This is my set up

```
return PromiseMixin.xhr(`${ENV.APP.URL_PREFIX}/person/${encodedIdentification}`, "GET").then((response) => {
          simpleStore.push("person", response);
});
```

Am i just not able to retrieve a single record without using the findById method?

**Comment by jasonmit** [comment]
This is an ember-data assertion.

https://github.com/emberjs/data/blob/master/addon/-private/system/model/model.js#L975-L978

**Comment by toranb** [comment]
@jasonmit is this an issue supporting both ember-data and simple-store together?

@jwright04 any chance you could provide a full stack trace to help us better identify when the error occurs?

**Comment by jasonmit** [comment]
@toranb hard to tell with the information given.  But simpleStore in the above snippet may be the ember data store.

**Comment by jwright04** [comment]
Thanks for the response guys.  Here is the full error:

```
ember.debug.js:32161 
Error: You should not call `create` on a model. Instead, call `store.createRecord` with the attributes you would like to set.
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:26689:21)
    at Function.create (http://localhost:4200/assets/vendor.js:95456:13)
    at buildRecord (http://localhost:4200/assets/vendor.js:91537:30)
    at Class.push (http://localhost:4200/assets/vendor.js:91607:26)
    at http://localhost:4200/assets/lpc-app.js:1108:29
    at tryCatch (http://localhost:4200/assets/vendor.js:63756:14)
    at invokeCallback (http://localhost:4200/assets/vendor.js:63771:15)
    at publish (http://localhost:4200/assets/vendor.js:63739:9)
    at http://localhost:4200/assets/vendor.js:42189:7
onerrorDefault @ ember.debug.js:32161
trigger @ ember.debug.js:54356
(anonymous function) @ ember.debug.js:55605
invoke @ ember.debug.js:333
flush @ ember.debug.js:397
flush @ ember.debug.js:205
end @ ember.debug.js:560
run @ ember.debug.js:682
run @ ember.debug.js:21239
hash.success @ promise.js:13
fire @ jquery.js:3187
fireWith @ jquery.js:3317
done @ jquery.js:8785
(anonymous function) @ jquery.js:9151
```

Just to give you a little background, i'm using ember simple auth.  Once I successfully receive an authentication token (within my `authenticateSuccess` function), i then attempt to make this call within that callback:

```
return PromiseMixin.xhr(`${ENV.APP.URL_PREFIX}/person/${encodedIdentification}`, "GET").then((response) => {
          simpleStore.push("person", response);
});
```

That's when I get the error.

**Comment by jasonmit** [comment]
Can you post the entire class that function is within.  I am fairly certain that simpleStore is actually the ember data store service that is injected instead of simple store.  Also, which version of ember simple store are you using?

**Comment by jwright04** [comment]
Here it is:

```
import Ember from 'ember';
import ENV from 'app/config/environment';
import PromiseMixin from 'ember-promise/mixins/promise';

export default Ember.Service.extend({
    store       : Ember.inject.service(),
    simpleStore : Ember.inject.service(),
    authenticateSuccess(identification){
        var encodedIdentification = encodeURIComponent(identification);
        var simpleStore           = this.get("simpleStore");

        return PromiseMixin.xhr(`${ENV.APP.URL_PREFIX}/person/${encodedIdentification}`, "GET")
                           .then((response) => {
                               return simpleStore.push("person", response);
                           });
    }
});
```

**Comment by jasonmit** [comment]
The stack trace indicates it's happening within the ember-data store and not the ember-cli-simple-store.  I would pause on `buildRecord (http://localhost:4200/assets/vendor.js:91537:30)` to see how that is being invoked after you push records into the simple store.  Perhaps you have a computed property, observer, or the caller of `authenticateSuccess` which is touching ember-data.

**Comment by toranb** [comment]
@jwright04 if you need help debugging this just reach out - I'd be glad to pair up over screen hero or something this week if you need a hand :)

if you got this, a full screenshot of the pause'd buildRecord would be great as @jasonmit suggested

**Comment by toranb** [comment]
Closing for inactivity - if you get back into this and need help just let me know
